// Content build: compile, validate, write packs, manifests and readable outputs.
//   node tools/content/build.ts                 write outputs; exit 1 on validation errors
//   node tools/content/build.ts --check         also fail if committed outputs are stale
//   node tools/content/build.ts --only case03   validate Stage 1 + one case; write only that case's packs and scripts
//
// Pack tiers: Stage 1 (released, PACK_IDS) is strict about assets. Stage 2 production packs
// (PRODUCTION_PACK_IDS: cases 2–4 and cozy) report assets A has not delivered as requests
// (docs/content/ASSET_REQUESTS.md). Preview packs (cases 5–8) skip asset checks.
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { cozySource, preview, production, sharedSource, stage1 } from '../../content/index.ts';
import { genderReview } from '../../content/shared/gender-review.ts';
import { build } from './compile.ts';
import { renderAssetRequests, renderChangelog, renderReport, renderVariant } from './render.ts';
import type { AssetTier } from './staging.ts';

const ROOT = join(import.meta.dirname, '..', '..');
const check = process.argv.includes('--check');
const onlyArg = process.argv.indexOf('--only');
const only = onlyArg > 0 ? process.argv[onlyArg + 1] : undefined;
const later = [...production, ...preview];
const cases = only ? [...stage1, ...later.filter((c) => c.id === only || c.id === 'stage2-common')] : [...stage1, ...later];
if (only && !cases.some((c) => c.id === only)) throw new Error(`unknown case ${only}`);

const stage1Ids = new Set(['shared', ...stage1.flatMap((c) => c.variants.map((v) => v.pack))]);
const productionIds = new Set(['cozy', ...production.flatMap((c) => c.variants.map((v) => v.pack))]);
const tier = (pack: string): AssetTier => (stage1Ids.has(pack) ? 'strict' : productionIds.has(pack) ? 'pending' : 'skip');

const result = build(sharedSource, cases, genderReview, { tier, cozy: only ? null : cozySource });
const files = new Map<string, string>();
const json = (v: unknown) => `${JSON.stringify(v, null, 1)}\n`;
for (const p of result.packs) files.set(`packages/content/packs/${p.id}.json`, json(p));

// Voice manifests: released + production (A records these), and preview (not for production).
const recordIds = new Set([...stage1Ids, ...productionIds]);
const subset = (keep: (pack: string) => boolean) => ({
  ...result.manifest,
  packs: Object.fromEntries(Object.entries(result.manifest.packs).filter(([k]) => keep(k))),
  entries: result.manifest.entries.filter((e) => e.packs.some(keep)).map((e) => ({ ...e, packs: e.packs.filter(keep) })),
});
files.set('packages/content/voice-manifest.json', json(subset((p) => recordIds.has(p))));
files.set('packages/content/voice-manifest.stage2-preview.json', json(subset((p) => !recordIds.has(p))));

const packIds = result.packs.map((p) => p.id);
files.set('packages/content/src/packs.ts', [
  '// Generated by tools/content/build.ts. Do not edit.',
  "import type { ContentPack } from './schema.ts';",
  ...packIds.map((id, i) => `import p${i} from '../packs/${id}.json' with { type: 'json' };`),
  '',
  '/** Released packs (Stage 1). */',
  `export const PACK_IDS = ${JSON.stringify(packIds.filter((id) => stage1Ids.has(id)))} as const;`,
  '/** Stage 2 production packs (cases 2–4, cozy day): integrated and recorded during Stage 2. */',
  `export const PRODUCTION_PACK_IDS = ${JSON.stringify(packIds.filter((id) => productionIds.has(id)))} as const;`,
  '/** Preparatory packs (cases 5–8): validated, not for production before «дальше». */',
  `export const PREVIEW_PACK_IDS = ${JSON.stringify(packIds.filter((id) => !stage1Ids.has(id) && !productionIds.has(id)))} as const;`,
  'export const packs: Readonly<Record<string, ContentPack>> = {',
  ...packIds.map((id, i) => `  '${id}': p${i} as unknown as ContentPack,`),
  '};',
  '',
].join('\n'));
for (const c of cases) for (const v of c.variants) {
  const pack = result.packs.find((p) => p.id === v.pack)!;
  files.set(`docs/content/scripts/${v.pack}.md`, renderVariant(result, v, pack) + '\n');
}
files.set('docs/content/CHANGELOG_RU.md', renderChangelog(result) + '\n');
files.set('docs/content/VALIDATION_REPORT.md', renderReport(result) + '\n');
files.set('docs/content/ASSET_REQUESTS.md', renderAssetRequests(result) + '\n');

let stale = 0;
if (only) for (const rel of [...files.keys()]) if (!rel.includes(`/${only}-`)) files.delete(rel);
for (const [rel, text] of files) {
  const abs = join(ROOT, rel);
  if (check) {
    if (!existsSync(abs) || readFileSync(abs, 'utf8') !== text) { stale++; console.error(`stale: ${rel}`); }
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, text);
  }
}
const errors = result.issues.filter((i) => i.level === 'error');
const warnings = result.issues.filter((i) => i.level === 'warning');
const pending = warnings.filter((i) => i.code === 'ASSET-PENDING');
for (const i of [...errors, ...warnings.filter((w) => w.code !== 'ASSET-PENDING')].slice(0, 200)) console.log(`${i.level === 'error' ? 'ERROR' : 'warn '} ${i.code} ${i.where}: ${i.message}`);
console.log(`packs: ${result.packs.map((p) => p.id).join(', ')}`);
console.log(`manifest entries: ${result.manifest.entries.length}; errors: ${errors.length}; warnings: ${warnings.length - pending.length}; pending assets: ${result.assetRequests.length}${check ? `; stale: ${stale}` : ''}`);
if (errors.length || stale) process.exit(1);
