// Content build: compile, validate, write packs, manifest and readable outputs.
//   node tools/content/build.ts           write outputs; exit 1 on validation errors
//   node tools/content/build.ts --check   also fail if committed outputs are stale
//   node tools/content/build.ts --stage2  include preparatory cases 2–8 (C2)
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { sharedSource, stage1, stage2 } from '../../content/index.ts';
import { genderReview } from '../../content/shared/gender-review.ts';
import { build } from './compile.ts';
import { renderChangelog, renderReport, renderVariant } from './render.ts';

const ROOT = join(import.meta.dirname, '..', '..');
const check = process.argv.includes('--check');
const withStage2 = process.argv.includes('--stage2') || stage2.length > 0;
const cases = withStage2 ? [...stage1, ...stage2] : stage1;

const result = build(sharedSource, cases, genderReview);
const files = new Map<string, string>();
const json = (v: unknown) => `${JSON.stringify(v, null, 1)}\n`;
const stage1Ids = new Set(['shared', ...stage1.flatMap((c) => c.variants.map((v) => v.pack))]);
for (const p of result.packs) files.set(`packages/content/packs/${p.id}.json`, json(p));
const s1manifest = { ...result.manifest, packs: Object.fromEntries(Object.entries(result.manifest.packs).filter(([k]) => stage1Ids.has(k))), entries: result.manifest.entries.filter((e) => e.packs.some((p) => stage1Ids.has(p))) };
files.set('packages/content/voice-manifest.json', json(s1manifest));
if (withStage2) files.set('packages/content/voice-manifest.stage2-preview.json', json(result.manifest));
const packIds = result.packs.map((p) => p.id);
files.set('packages/content/src/packs.ts', [
  '// Generated by tools/content/build.ts. Do not edit.',
  "import type { ContentPack } from './schema.ts';",
  ...packIds.map((id, i) => `import p${i} from '../packs/${id}.json' with { type: 'json' };`),
  '',
  `export const PACK_IDS = ${JSON.stringify(packIds.filter((id) => stage1Ids.has(id)))} as const;`,
  `/** Preparatory packs (cases 2–8): validated, not for production before «дальше». */`,
  `export const PREVIEW_PACK_IDS = ${JSON.stringify(packIds.filter((id) => !stage1Ids.has(id)))} as const;`,
  'export const packs: Readonly<Record<string, ContentPack>> = {',
  ...packIds.map((id, i) => `  '${id}': p${i} as unknown as ContentPack,`),
  '};',
  '',
].join('\n'));
for (const c of cases) for (const v of c.variants) {
  const pack = result.packs.find((p) => p.id === v.pack)!;
  files.set(`docs/content/scripts/${v.pack}.md`, renderVariant(result, v, pack) + '\n');
}
files.set('docs/content/CHANGELOG_RU.md', renderChangelog(result) + '\n');
files.set('docs/content/VALIDATION_REPORT.md', renderReport(result) + '\n');

let stale = 0;
for (const [rel, text] of files) {
  const abs = join(ROOT, rel);
  if (check) {
    if (!existsSync(abs) || readFileSync(abs, 'utf8') !== text) { stale++; console.error(`stale: ${rel}`); }
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, text);
  }
}
const errors = result.issues.filter((i) => i.level === 'error');
const warnings = result.issues.filter((i) => i.level === 'warning');
for (const i of [...errors, ...warnings].slice(0, 200)) console.log(`${i.level === 'error' ? 'ERROR' : 'warn '} ${i.code} ${i.where}: ${i.message}`);
console.log(`packs: ${result.packs.map((p) => p.id).join(', ')}`);
console.log(`manifest entries: ${result.manifest.entries.length}; errors: ${errors.length}; warnings: ${warnings.length}${check ? `; stale: ${stale}` : ''}`);
if (errors.length || stale) process.exit(1);