// Generates content/caseNN/lines-pm.ts with every ID-bearing line of case N exactly as in the PM
// scripts (speaker mapped, kind guessed). Authors then adjust kinds, add labels (R06) and record
// corrections. Usage: node tools/content/scaffold-case.ts 2
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { readPmLines } from './pm-import.ts';

const SPEAKERS: Record<string, string> = {
  Хвостс: 'khvosts', Ватсони: 'watsony', Пудинг: 'pudding', Тёпа: 'tyopa', Фитилёк: 'fitilyok', Картофан: 'kartofan',
  Стелла: 'stella', Мышонок: 'mouse', Дамка: 'damka', Пухлик: 'pukhlik', Все: 'all',
};

const n = Number(process.argv[2]);
if (!(n >= 2 && n <= 8)) throw new Error('case number 2–8');
const nn = String(n).padStart(2, '0');
const rows = readPmLines().filter((l) => l.file.startsWith(`SCRIPT_CASE${nn}`));
const esc = (s: string) => s.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
const out = [
  `// Case ${n}: every ID-bearing line from SCRIPT_CASE${nn}_RU.md and SCRIPT_CASE${nn}_LEVELS23_RU.md,`,
  '// generated by tools/content/scaffold-case.ts, then curated. Text must match PM unless a change is recorded.',
  "import { lines } from '../../tools/content/dsl.ts';",
  '',
  `export const linesPm = lines('case${nn}/pm', 'dialogue', [`,
];
for (const l of rows) {
  const raw = l.speaker ?? '';
  const base = raw.replace(/\s*\(.*\)\s*$/u, '');
  const aside = raw.match(/\((.*)\)/u)?.[1];
  let speaker = SPEAKERS[base] ?? 'narrator';
  let kind = 'dialogue';
  if (/-H-/.test(l.id)) { kind = 'hint'; if (!raw) speaker = 'khvosts'; }
  else if (/-R-/.test(l.id)) { kind = 'hint'; if (!raw) speaker = 'watsony'; }
  else if (/-L-/.test(l.id)) kind = 'comfort';
  else if (!raw) kind = 'fact'; // unattributed: usually «А ты знал?» cards; check
  const opts = [kind !== 'dialogue' ? `kind: '${kind}'` : '', aside ? `note: '${esc(aside)}'` : ''].filter(Boolean);
  const unknown = raw && !SPEAKERS[base] ? ` // TODO speaker «${raw}»` : '';
  out.push(`  ['${l.id}', '${speaker}', '${esc(l.text)}'${opts.length ? `, { ${opts.join(', ')} }` : ''}],${unknown} // ${l.file}:${l.line}`);
}
out.push(']);', '');
const dir = join(import.meta.dirname, '..', '..', 'content', `case${nn}`);
mkdirSync(dir, { recursive: true });
const file = join(dir, 'lines-pm.ts');
if (existsSync(file) && !process.argv.includes('--force')) throw new Error(`${file} exists (use --force)`);
writeFileSync(file, out.join('\n'));
console.log(`${rows.length} lines → ${file}`);
