// Generated by tools/content/build.ts. Do not edit.
import type { ContentPack } from './schema.ts';
import p0 from '../packs/shared.json' with { type: 'json' };
import p1 from '../packs/prologue.json' with { type: 'json' };
import p2 from '../packs/case01-l1.json' with { type: 'json' };
import p3 from '../packs/case01-l2.json' with { type: 'json' };
import p4 from '../packs/case01-l3.json' with { type: 'json' };

export const PACK_IDS = ["shared","prologue","case01-l1","case01-l2","case01-l3"] as const;
/** Preparatory packs (cases 2–8): validated, not for production before «дальше». */
export const PREVIEW_PACK_IDS = [] as const;
export const packs: Readonly<Record<string, ContentPack>> = {
  'shared': p0 as unknown as ContentPack,
  'prologue': p1 as unknown as ContentPack,
  'case01-l1': p2 as unknown as ContentPack,
  'case01-l2': p3 as unknown as ContentPack,
  'case01-l3': p4 as unknown as ContentPack,
};
