"""Build optimized runtime assets from masters and write assets/manifest.json (plan 5.7).

python tools/assets/build.py [--only backgrounds,props,puppets,ui,sfx,music,voice] [--check]

* Selection of masters, output ids, packs and hotspots: tools/assets/catalog.json.
* Image provenance: the azure-image-generation result JSON saved next to every master
  (prompt hash, references, quality, model deployment, timestamp).
* Missing provenance is an error (plan 5.7). `--check` validates the manifest against the
  files on disk without rebuilding anything.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
ASSETS = REPO / "assets"
MASTERS = Path("F:/AI/GameAssets/fluffy-bureau")
MANIFEST = ASSETS / "manifest.json"
MAX_SIDE = 4096

LIC_IMAGE = ("Generated by the project with Azure OpenAI image model gpt-image-2.5 (owner's deployment); "
             "output owned by the project under the Microsoft Product Terms. No third-party artwork used.")
LIC_SPEECH = ("Generated with Azure AI Speech prebuilt neural voices under the owner's subscription; "
              "commercial use permitted under the Microsoft Product Terms.")
LIC_OWN = "Original work by the Fluffy Bureau team (workstream A). Licence: CC0 1.0."
LIC_MUSIC = ("Generated locally with ACE-Step 1.5 XL-SFT (model weights Apache-2.0); output owned by the "
             "project. No samples or third-party recordings used.")


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def gen_provenance(master: Path, notes: str = "") -> dict:
    """Provenance from the generation JSON beside a master image."""
    stem = master.with_suffix("")
    base = Path(str(stem).rsplit("-c", 1)[0]) if stem.name.rsplit("-c", 1)[-1].isdigit() else stem
    for cand in (stem.with_suffix(".json"), base.with_suffix(".json")):
        if cand.exists():
            g = json.loads(cand.read_text(encoding="utf-8"))
            break
    else:
        raise FileNotFoundError(f"no generation provenance for {master}")
    job = g.get("job", {})
    refs = [Path(r["path"]).name if isinstance(r, dict) else Path(r).name for r in g.get("reference_images") or []]
    created = datetime.fromtimestamp(cand.stat().st_mtime, timezone.utc).isoformat(timespec="seconds")
    prompt = job.get("prompt_file", "")
    try:
        prompt = str(Path(prompt).resolve().relative_to(REPO)).replace("\\", "/")
    except ValueError:
        prompt = Path(prompt).name
    return {"tool": f"Azure OpenAI gpt-image-2.5-sunburst ({g.get('operation')}, quality {g.get('quality')})",
            "source": f"master {master.name} sha256:{sha256(master)[:16]}; prompt {prompt} sha256:{g.get('prompt_sha256', '')[:16]}"
                      + (f"; references {', '.join(refs)}" if refs else ""),
            "createdAt": created, "licence": LIC_IMAGE, "notes": notes}


def to_webp(img: Image.Image, out: Path, quality: int = 86, lossless: bool = False) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    if max(img.size) > MAX_SIDE:
        raise ValueError(f"{out} exceeds {MAX_SIDE}px")
    img.save(out, "WEBP", quality=quality, method=6, lossless=lossless, exact=img.mode == "RGBA")


def entry(aid: str, path: Path, pack: str, kind: str, prov: dict, w=None, h=None, dur=None) -> dict:
    return {"id": aid, "path": str(path.relative_to(ASSETS)).replace("\\", "/"), "pack": pack, "kind": kind,
            "width": w, "height": h, "durationMs": dur, "format": path.suffix.lstrip("."),
            "bytes": path.stat().st_size, "sha256": sha256(path), "provenance": prov}


def build_backgrounds(cat: dict) -> tuple[list, dict]:
    out, bgs = [], {}
    for bid, spec in cat["backgrounds"].items():
        src = MASTERS / spec["master"]
        dst = ASSETS / "bg" / f"{bid.split('.', 1)[1]}.webp"
        im = Image.open(src).convert("RGB")
        if im.size != (2560, 1600):
            im = im.resize((2560, 1600), Image.LANCZOS)
        to_webp(im, dst, spec.get("quality", 84))
        out.append(entry(bid, dst, spec["pack"], "background", gen_provenance(src, spec.get("notes", "")), 2560, 1600))
        bgs[bid] = {"location": spec.get("location"), "hotspots": spec.get("hotspots", {})}
        if spec.get("layers"):
            bgs[bid]["layers"] = spec["layers"]
    return out, bgs


def trim(img: Image.Image, pad: int = 2) -> Image.Image:
    a = img.getchannel("A").point(lambda v: 0 if v < 8 else v)
    img.putalpha(a)
    bb = a.getbbox()
    img = img.crop(bb)
    canvas = Image.new("RGBA", (img.width + 2 * pad, img.height + 2 * pad), (0, 0, 0, 0))
    canvas.paste(img, (pad, pad))
    return canvas


def build_props(cat: dict) -> list:
    out = []
    for pid, spec in cat["props"].items():
        src = MASTERS / spec["master"]
        im = trim(Image.open(src).convert("RGBA"))
        size = spec.get("size", 512)
        im.thumbnail((size, size), Image.LANCZOS)
        dst = ASSETS / spec.get("dir", "props") / f"{pid.split('.', 1)[1]}.webp"
        to_webp(im, dst, 90)
        out.append(entry(pid, dst, spec["pack"], spec.get("kind", "ui"), gen_provenance(src, spec.get("notes", "")),
                         im.width, im.height))
    return out


def build_puppets(cat: dict) -> list:
    out = []
    for cid, spec in cat["puppets"].items():
        cfg = REPO / "tools/assets/art/puppets" / f"{spec['config']}.json"
        subprocess.run([sys.executable, str(HERE / "art/puppet.py"), "assemble", str(cfg),
                        "--out", str(ASSETS / spec["dir"])], check=True, capture_output=True)
        folder = ASSETS / spec["dir"] / spec["name"]
        conf = json.loads(cfg.read_text(encoding="utf-8"))
        master = MASTERS / conf["base"]
        prov = gen_provenance(master, "Base figure; face variants from masked edits of the same head "
                                      f"(F:/AI/GameAssets/fluffy-bureau/puppets/{conf.get('dir', conf['id'])}/edits, each with its own generation JSON). "
                                      "Cut, packed and rigged by tools/assets/art/puppet.py.")
        kind = "avatar-layer" if "avatar" in conf else "character-layer"
        for f in sorted(folder.iterdir()):
            fid = f"{cid}.{f.name}"
            if f.suffix == ".webp":
                w, h = Image.open(f).size
                out.append(entry(fid, f, spec["pack"], kind, prov, w, h))
            else:
                out.append(entry(fid, f, spec["pack"], kind, prov))
    return out


def build_staging() -> list:
    out = []
    subprocess.run([sys.executable, str(HERE / "art/staging.py")], check=True, capture_output=True)
    src = json.loads((MASTERS / "staging-sources.json").read_text(encoding="utf-8"))
    own = {"tool": "tools/assets/art/staging.py", "source": "hand-authored keyframes", "createdAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
           "licence": LIC_OWN, "notes": "aegis-clip/1 motion for T25 cutscenes."}
    for f in sorted((ASSETS / "staging/clips").glob("*.clip.json")):
        out.append(entry(f"clip.{f.name.split('.')[0]}", f, "shell", "clip", own))
    for group, kind in (("props", "prop-puppet"), ("acc", "avatar-layer"), ("fx", "effect")):
        for d in sorted(p for p in (ASSETS / "staging" / group).iterdir()):
            files = [d] if d.is_file() else sorted(d.iterdir())
            rid = d.name if d.is_dir() else "fx.atlas"
            masters = src["sources"].get(rid, [])
            master = None
            if masters:
                m0 = MASTERS / masters[0]
                master = m0 if m0.exists() else m0.with_name(m0.stem + "-c1.png")
            prov = gen_provenance(master, f"Built by tools/assets/art/staging.py from {', '.join(masters)}.") if master else own
            for f in files:
                if f.suffix == ".webp":
                    w, h = Image.open(f).size
                    out.append(entry(f"{rid}:{f.name}" if group != "fx" else f"fx:{f.name}", f, "shell", kind, prov, w, h))
                else:
                    out.append(entry(f"{rid}:{f.name}" if group != "fx" else f"fx:{f.name}", f, "shell", kind, prov))
    return out


def build_ui() -> list:
    out = []
    prov = {"tool": "tools/assets/art/ui_kit.py (hand-authored SVG)", "source": "tools/assets/art/ui_kit.py",
            "createdAt": datetime.now(timezone.utc).isoformat(timespec="seconds"), "licence": LIC_OWN, "notes": ""}
    subprocess.run([sys.executable, str(HERE / "art/ui_kit.py")], check=True, capture_output=True)
    for f in sorted((ASSETS / "ui").rglob("*.svg")):
        rel = f.relative_to(ASSETS / "ui").with_suffix("")
        kind = "icon" if rel.parts[0] in ("icons", "stickers") else "ui"
        out.append(entry("ui." + ".".join(rel.parts), f, "shell", kind, prov))
    return out


def build_sfx() -> list:
    out = []
    subprocess.run([sys.executable, str(HERE / "audio/sfx.py")], check=True, capture_output=True)
    catalog = json.loads((MASTERS / "sfx/catalog.json").read_text(encoding="utf-8"))
    for name, c in catalog.items():
        f = ASSETS / "sfx" / c["file"]
        prov = {"tool": "tools/assets/audio/sfx.py (numpy synthesis, no samples)", "source": f"effect '{name}': {c['description']}",
                "createdAt": datetime.fromtimestamp(f.stat().st_mtime, timezone.utc).isoformat(timespec="seconds"),
                "licence": LIC_OWN, "notes": "Loudness -24 LUFS, true peak <= -3 dBTP."}
        out.append(entry(f"sfx.{name}", f, "shell", "sfx", prov, dur=c["durationMs"]))
    return out


def build_music() -> list:
    out = []
    idx = ASSETS / "music/index.json"
    if not idx.exists():
        return out
    for mid, m in json.loads(idx.read_text(encoding="utf-8")).items():
        f = ASSETS / "music" / m["file"]
        prov = {"tool": m["tool"], "source": m["source"], "createdAt": m["createdAt"], "licence": LIC_MUSIC, "notes": m.get("notes", "")}
        out.append(entry(f"music.{mid}", f, m.get("pack", "shell"), "music", prov, dur=m["durationMs"]))
    return out


def build_voice() -> list:
    out = []
    idx = ASSETS / "voice/index.json"
    if not idx.exists():
        return out
    lines = json.loads(idx.read_text(encoding="utf-8"))["lines"]
    seen = set()
    for lid, r in lines.items():
        if r.get("sameAudioAs") or r["file"] in seen:
            continue
        seen.add(r["file"])
        prov = {**r["provenance"], "source": f"line {lid} rev {r['revision']} ttsHash {str(r.get('ttsHash'))[:16]}"}
        prov.setdefault("licence", LIC_SPEECH)
        for f, kind in ((ASSETS / "voice" / r["file"], "voice"), (ASSETS / "voice" / r["cues"], "cues")):
            out.append(entry(f"{kind}.{lid}", f, r["pack"], kind, prov, dur=r["durationMs"]))
    return out


def check(manifest: dict) -> int:
    errors = 0
    for a in manifest["assets"]:
        f = ASSETS / a["path"]
        p = a.get("provenance") or {}
        if not f.exists():
            print("MISSING", a["id"], a["path"]); errors += 1
        elif a.get("sha256") and sha256(f) != a["sha256"]:
            print("STALE", a["id"]); errors += 1
        for k in ("tool", "source", "createdAt", "licence"):
            if not p.get(k):
                print("PROVENANCE", a["id"], k); errors += 1
        if a["format"] == "webp" and (a.get("width") or 0) > MAX_SIDE:
            print("TOO BIG", a["id"]); errors += 1
    seen_ids: set = set()
    for a in manifest["assets"]:
        if a["id"] in seen_ids:
            print("DUPLICATE ID", a["id"]); errors += 1
        seen_ids.add(a["id"])
    for section in ("characters", "avatar", "voice"):
        for key, refs in manifest.get(section, {}).items():
            for field, ref in refs.items():
                if isinstance(ref, str) and field not in ("ttsHash",) and ref not in seen_ids:
                    print("DANGLING", section, key, field, ref); errors += 1
    listed = {a["path"] for a in manifest["assets"]}
    for f in ASSETS.rglob("*"):
        rel = str(f.relative_to(ASSETS)).replace("\\", "/")
        if f.is_file() and rel not in listed and rel not in ("manifest.json", "voice/index.json", "music/index.json"):
            print("UNLISTED", rel); errors += 1
    total = sum(f.stat().st_size for f in ASSETS.rglob("*") if f.is_file())
    print(f"{len(manifest['assets'])} assets, {total / 1e6:.1f} MB, {errors} errors")
    return errors


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    if a.check:
        sys.exit(1 if check(json.loads(MANIFEST.read_text(encoding="utf-8"))) else 0)
    cat = json.loads((HERE / "catalog.json").read_text(encoding="utf-8"))
    old = json.loads(MANIFEST.read_text(encoding="utf-8")) if MANIFEST.exists() else {"assets": [], "backgrounds": {}}
    groups = set(filter(None, a.only.split(","))) or {"backgrounds", "props", "puppets", "ui", "sfx", "music", "voice", "staging"}
    owners = {"backgrounds": ("bg/",), "props": ("props/", "avatar/hats/"), "puppets": ("characters/", "avatar/"),
              "ui": ("ui/",), "sfx": ("sfx/",), "music": ("music/",), "voice": ("voice/",), "staging": ("staging/",), "index": ()}

    def owned(path: str, g: str) -> bool:
        if g == "puppets" and path.startswith("avatar/hats/"):
            return False
        return bool(owners[g]) and path.startswith(owners[g])

    keep = [x for x in old["assets"] if not any(owned(x["path"], g) for g in groups)]
    for x in keep:
        f = ASSETS / x["path"]
        if f.exists():
            x["bytes"], x["sha256"] = f.stat().st_size, sha256(f)
    assets, bgs = list(keep), dict(old.get("backgrounds", {}))
    if "backgrounds" in groups:
        b, bgs = build_backgrounds(cat)
        assets += b
    if "props" in groups:
        assets += build_props(cat)
    if "puppets" in groups:
        assets += build_puppets(cat)
    if "ui" in groups:
        assets += build_ui()
    if "sfx" in groups:
        assets += build_sfx()
    if "music" in groups:
        assets += build_music()
    if "voice" in groups:
        assets += build_voice()
    if "staging" in groups:
        assets += build_staging()
    assets.sort(key=lambda x: x["id"])
    ids = {x["id"] for x in assets}
    characters = {c: {"base": f"char.{c}.base.webp", "rig": f"char.{c}.{c}.rig.json", "atlas": f"char.{c}.{c}.atlas.json", "atlasImage": f"char.{c}.{c}.atlas.webp"}
                  for c in (p["name"] for k, p in cat["puppets"].items() if k.startswith("char.")) if f"char.{c}.base.webp" in ids}
    avatar = {s: {"base": f"avatar.{s}.base.webp", "scarfMask": f"avatar.{s}.scarf-mask.webp",
                  "rig": f"avatar.{s}.avatar.{s}.rig.json", "atlas": f"avatar.{s}.avatar.{s}.atlas.json",
                  "atlasImage": f"avatar.{s}.avatar.{s}.atlas.webp"}
              for s in (p["name"] for k, p in cat["puppets"].items() if k.startswith("avatar.")) if f"avatar.{s}.base.webp" in ids}
    hats = {x["id"].split(".", 1)[1]: x["id"] for x in assets if x["path"].startswith("avatar/hats/")}
    voice = {}
    vidx = ASSETS / "voice/index.json"
    if vidx.exists():
        for lid, r in json.loads(vidx.read_text(encoding="utf-8"))["lines"].items():
            src = r.get("sameAudioAs") or lid
            voice[lid] = {"asset": f"voice.{src}", "cues": f"cues.{src}", "durationMs": r["durationMs"],
                          "revision": r["revision"], "ttsHash": r.get("ttsHash")}
    music = {x["id"].split(".", 1)[1]: x["id"] for x in assets if x["kind"] == "music"}
    sfx = {x["id"].split(".", 1)[1]: x["id"] for x in assets if x["kind"] == "sfx"}
    staging = {"rigs": {}, "clips": {}, "fx": {}}
    for x in assets:
        if x["path"].startswith("staging/clips/"):
            staging["clips"][x["id"].split(".", 1)[1]] = x["id"]
        elif x["path"].startswith(("staging/props/", "staging/acc/")):
            rid, fname = x["id"].split(":", 1)
            key = "rig" if fname.endswith(".rig.json") else "atlas" if fname.endswith(".atlas.json") else "atlasImage"
            staging["rigs"].setdefault(rid, {})[key] = x["id"]
        elif x["path"].startswith("staging/fx/"):
            staging["fx"]["atlas" if x["id"].endswith(".json") else "atlasImage"] = x["id"]
    manifest = {"format": "fluffy-asset-manifest", "schema": 1, "assets": assets, "backgrounds": bgs,
                "characters": characters, "avatar": avatar, "hats": hats, "voice": voice, "music": music, "sfx": sfx,
                "staging": staging}
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=1) + "\n", encoding="utf-8", newline="\n")
    sys.exit(1 if check(manifest) else 0)


if __name__ == "__main__":
    main()
