import type { VariantSource } from '../../tools/content/dsl.ts';
import {
  activity, and, baseRewards, cl, collections, commonComfort, cutscene, eq, facts, factsScene, finalLightScene,
  glossary, goto, has, HUB, intended, introOffice, L, lightGame, menu, minigame, mopt, ne, not, opt, redHerringsBase, reveal, rewardScene,
  sceneProps, secretNote, secretNotesPage, seq, skill, soundGame, versionScene, where, what, who,
} from './common.ts';
import { intro, note, reveal as revealCutscene, reward as rewardCutscene } from './cutscenes.ts';

const anyWhat = { op: 'in' as const, axis: 'what', values: ['training', 'broken', 'ghost', 'repair'] };

export const level3: VariantSource = {
  pack: 'case03-l3',
  kind: 'case',
  title: 'C3-TITLE',
  case: { number: 3, level: 3 },
  start: 'C3-0',
  scenes: [
    { id: 'C3-0', title: 'Контора: вечерний гость', location: 'office-evening', cast: ['khvosts', 'watsony', 'mouse'], presentation: 'cutscene', props: sceneProps.map, steps: [cutscene('c3.intro.l3'), ...introOffice(), goto('C3-L3-1')] },
    { id: 'C3-L3-1', title: 'Берег Медового пруда', location: 'honey-pond', cast: ['pudding', 'damka', 'khvosts', 'watsony'], presentation: 'dialogue', steps: [...seq('C3-1-', 1, 5), ...seq('C3-L2-1-', 1, 3), ...seq('C3-L3-1-', 1, 2), skill('lamp', [L('C3-1-06')]), ...seq('C3-1-', 7, 8), L('C3-L2-1-04'), ...seq('C3-1-', 9, 10), goto(HUB)] },
    {
      id: HUB, title: 'Медовый пруд: выбор', location: 'honey-pond', cast: ['khvosts', 'watsony', 'pudding', 'damka', 'mouse'], presentation: 'hub',
      steps: [
        { t: 'if', when: { all: [has.clue('c3-l3-sounds'), has.clue('c3-l3-room'), has.clue('c3-tracks'), has.clue('c3-l3-log'), has.clue('c3-blink'), not(has.visited('C3-L3-9'))] }, then: [goto('C3-L3-9')], else: [] },
        menu('C3-L3-M', null, [
          mopt('sounds', 'C3-1-B01', 'C3-L3-2', { hideWhen: has.clue('c3-l3-sounds') }),
          mopt('door', 'C3-1-B02', 'C3-3', { when: has.clue('c3-l3-sounds'), hideWhen: has.visited('C3-3') }),
          mopt('mice', 'C3-1-B07', 'C3-L3-4', { hideWhen: has.visited('C3-L3-4') }),
          mopt('room', 'C3-1-B04', 'C3-L3-5', { when: has.visited('C3-3'), hideWhen: has.clue('c3-l3-room') }),
          mopt('tracks', 'C3-1-B05', 'C3-L3-6', { when: has.visited('C3-3'), hideWhen: has.clue('c3-tracks') }),
          mopt('log', 'C3-1-B06', 'C3-L3-8', { when: has.clue('c3-l3-room'), hideWhen: has.clue('c3-l3-log') }),
          mopt('blink', 'C3-1-B08', 'C3-L3-7', { when: { all: [has.visited('C3-L3-4'), has.clue('c3-l3-room')] }, hideWhen: has.clue('c3-blink') }),
        ]),
      ],
    },
    { id: 'C3-L3-2', title: 'Услышь разницу: похожие образцы', location: 'pond-bank', cast: ['khvosts', 'watsony', 'mouse'], presentation: 'minigame', steps: [skill('sound-diff', [L('C3-2-01'), L('C3-2-02')]), minigame('c3l3-sound'), L('C3-L2-2-02'), ...seq('C3-2-', 6, 9), reveal('c3-l3-sounds'), goto(HUB)] },
    secretNote('c3.note.l3', [L('C3-L2-3-01')]),
    { id: 'C3-L3-4', title: 'Мышата', location: 'pond-bank', cast: ['mouse', 'khvosts'], presentation: 'dialogue', steps: [...seq('C3-L3-4-', 1, 6), reveal('c3-mice'), goto(HUB)] },
    { id: 'C3-L3-5', title: 'Лупа наверху', location: 'lighthouse-room', cast: ['khvosts', 'watsony', 'damka'], presentation: 'minigame', steps: [skill('magnifier', [L('C3-5-01'), L('C3-L2-4-01')]), minigame('c3l3-magnifier'), L('C3-5-06'), L('C3-L3-5-02'), L('C3-5-08'), L('C3-L2-4-05'), reveal('c3-l3-room'), goto(HUB)] },
    { id: 'C3-L3-6', title: 'Кто наследил?', location: 'lighthouse-stairs', cast: ['khvosts', 'watsony'], presentation: 'minigame', steps: [skill('tracks', [L('C3-6-01')]), minigame('c3l3-tracks'), ...seq('C3-6-', 5, 6), reveal('c3-tracks'), goto(HUB)] },
    { id: 'C3-L3-7', title: 'Прочитай мигание', location: 'lighthouse-room', cast: ['khvosts', 'watsony'], presentation: 'minigame', steps: [skill('read-blink', seq('C3-L3-7-', 1, 2)), minigame('c3l3-blink'), ...seq('C3-L3-7-', 4, 6), reveal('c3-blink'), goto(HUB)] },
    { id: 'C3-L3-8', title: 'Лента времени', location: 'lighthouse-room', cast: ['khvosts', 'watsony'], presentation: 'minigame', steps: [skill('timeline', [L('C3-L2-6-01'), L('C3-L2-6-02')], [L('C3-L2-6-03')]), minigame('c3l3-timeline'), L('C3-L2-6-04'), L('C3-L2-6-05'), L('C3-L3-8-01'), L('C3-L2-6-06'), reveal('c3-l3-log'), goto(HUB)] },
    versionScene('C3-L3-9'),
    { id: 'C3-L3-10', title: 'Разрешение', location: 'lighthouse-room', cast: ['khvosts', 'watsony', 'pukhlik', 'damka', 'tyopa'], presentation: 'cutscene', steps: [cutscene('c3.reveal.l3'), goto('C3-L3-11')] },
    finalLightScene('C3-L3-11', 3, 'c3l3-light'),
    factsScene(),
    rewardScene(3, 'c3.reward.l3'),
  ],
  logic: {
    axes: [
      { id: 'who', title: 'C3-AX-who', values: [who.pukhlik, who.fitilyok, who.stella, who.damka, who.tyopa] },
      { id: 'where', title: 'C3-AX-where', values: [where.top, where.shed, where.reeds, where.pier, where.cauldron] },
      { id: 'what', title: 'C3-AX-what', values: [what.training, what.broken, what.ghost, what.repair] },
    ],
    intended,
    clues: [
      { id: 'c3-l3-sounds', title: 'C3-CL-l2-sounds', required: true, predicate: ne('what', 'ghost'), requires: [], source: 'C3-L3-2', summary: 'Запись слышит страницы, заслонку и капли; молоток не доказывает ремонт.' },
      { id: 'c3-l3-room', title: 'C3-CL-l3-room', required: true, predicate: and(eq('where', 'top'), ne('where', 'cauldron'), ne('what', 'broken'), ne('what', 'repair')), requires: ['c3-secret-note'], source: 'C3-L3-5', summary: 'Комната наверху, окно, шнурок и пыльные инструменты; книга закрыта.' },
      { id: 'c3-tracks', title: 'C3-CL-tracks', required: true, predicate: eq('who', 'pukhlik'), requires: ['c3-secret-note'], source: 'C3-L3-6', summary: 'Следы совы исключают остальных жителей.' },
      { id: 'c3-l3-log', title: 'C3-CL-l3-log', required: true, predicate: and(ne('who', 'damka'), ne('who', 'tyopa'), ne('where', 'cauldron'), ne('what', 'repair')), requires: ['c3-l3-room'], source: 'C3-L3-8', summary: 'Журнал показывает, что котёл погас раньше, Дамка дома, ремонта не было.' },
      { id: 'c3-blink', title: 'C3-CL-blink', required: true, predicate: and(eq('what', 'training'), ne('what', 'broken'), ne('what', 'ghost')), requires: ['c3-l3-room'], source: 'C3-L3-7', summary: 'Рисунок мышат совпал с уроком «Привет».' },
      { id: 'c3-mice', title: 'C3-CL-mice', required: false, predicate: anyWhat, requires: [], source: 'C3-L3-4', summary: 'Мышата исправили ошибку: огоньков было три.' },
      { id: 'c3-secret-note', title: 'C3-COL-secret-note', required: false, predicate: anyWhat, requires: [], source: 'C3-3', summary: 'Первая Тайная заметка: запах ромашки у весла Дамки.' },
    ],
    version: { button: 'UI-hud.version', available: has.visited('C3-L3-9'), onSolved: 'C3-L3-10' },
    wrongVersion: {
      intro: [cl('C3-7-04')],
      byValue: [
        { axis: 'who', value: 'fitilyok', clues: ['c3-tracks'], lines: [cl('C3-7-05')] },
        { axis: 'who', value: 'stella', clues: ['c3-tracks'], lines: [cl('C3-7-06')] },
        { axis: 'who', value: 'damka', clues: ['c3-l3-log'], lines: [cl('C3-L2-7-01')] },
        { axis: 'who', value: 'tyopa', clues: ['c3-tracks'], lines: [cl('C3-L3-9-01')] },
        { axis: 'where', value: 'shed', clues: ['c3-l3-room'], lines: [cl('C3-7-07')] },
        { axis: 'where', value: 'reeds', clues: ['c3-l3-room'], lines: [cl('C3-7-08')] },
        { axis: 'where', value: 'pier', clues: ['c3-l3-room'], lines: [cl('C3-L2-7-02')] },
        { axis: 'where', value: 'cauldron', clues: ['c3-l3-log'], lines: [cl('C3-L3-9-02')] },
        { axis: 'what', value: 'broken', clues: ['c3-blink'], lines: [cl('C3-L3-9-03')] },
        { axis: 'what', value: 'ghost', clues: ['c3-l3-sounds'], lines: [cl('C3-7-10')] },
        { axis: 'what', value: 'repair', clues: ['c3-l3-room', 'c3-l3-log'], lines: [cl('C3-L2-7-03')] },
      ],
      outro: [cl('C3-7-11')],
    },
    redHerrings: [
      ...redHerringsBase,
      { id: 'rh-c3-damka-key', summary: 'Ключ у Дамки, но Пухлик влетел через окно.', presentedBy: ['C3-L2-1-01'], explainedBy: ['C3-L2-8-01', 'C3-L2-8-02'] },
      { id: 'rh-c3-tyopa-bubbles', summary: 'Пузыри Тёпы блестели вечером, но не мигали ночью.', presentedBy: ['C3-L3-1-01', 'C3-L3-1-02'], explainedBy: ['C3-L3-10-01', 'C3-L3-10-02'] },
    ],
  },
  notebookHelp: {
    mode: 'point',
    marks: [
      { axis: 'who', value: 'pukhlik', mark: 'confirmed', clues: ['c3-tracks'], line: 'C3-NB-01' },
      { axis: 'who', value: 'fitilyok', mark: 'excluded', clues: ['c3-tracks'], line: 'C3-NB-02' },
      { axis: 'who', value: 'stella', mark: 'excluded', clues: ['c3-tracks'], line: 'C3-NB-03' },
      { axis: 'who', value: 'damka', mark: 'excluded', clues: ['c3-l3-log'], line: 'C3-NB-10' },
      { axis: 'who', value: 'tyopa', mark: 'excluded', clues: ['c3-tracks'], line: 'C3-NB-14' },
      { axis: 'where', value: 'top', mark: 'confirmed', clues: ['c3-l3-room'], line: 'C3-NB-04' },
      { axis: 'where', value: 'shed', mark: 'excluded', clues: ['c3-l3-room'], line: 'C3-NB-05' },
      { axis: 'where', value: 'reeds', mark: 'excluded', clues: ['c3-l3-room'], line: 'C3-NB-06' },
      { axis: 'where', value: 'pier', mark: 'excluded', clues: ['c3-l3-room'], line: 'C3-NB-11' },
      { axis: 'where', value: 'cauldron', mark: 'excluded', clues: ['c3-l3-log'], line: 'C3-NB-13' },
      { axis: 'what', value: 'training', mark: 'confirmed', clues: ['c3-blink'], line: 'C3-NB-15' },
      { axis: 'what', value: 'broken', mark: 'excluded', clues: ['c3-blink'], line: 'C3-NB-16' },
      { axis: 'what', value: 'ghost', mark: 'excluded', clues: ['c3-l3-sounds'], line: 'C3-NB-09' },
      { axis: 'what', value: 'repair', mark: 'excluded', clues: ['c3-l3-room', 'c3-l3-log'], line: 'C3-NB-12' },
    ],
    pointers: [
      { clue: 'c3-l3-sounds', line: 'C3-L3-NB-01' },
      { clue: 'c3-l3-room', line: 'C3-L3-NB-02' },
      { clue: 'c3-tracks', line: 'C3-L3-NB-03' },
      { clue: 'c3-l3-log', line: 'C3-L3-NB-04' },
      { clue: 'c3-blink', line: 'C3-L3-NB-06' },
    ],
    nothing: 'UI-notebook.nothing',
  },
  hints: { klubok: { speaker: 'khvosts', precision: 'exact', allowance: 3, rules: [
    { id: 'C3-L3-H-01', when: not(has.clue('c3-l3-sounds')), cites: [] },
    { id: 'C3-L3-H-02', when: not(has.visited('C3-L3-4')), cites: [] },
    { id: 'C3-L3-H-03', when: not(has.clue('c3-blink')), cites: [] },
    { id: 'C3-L3-H-04', when: not(has.clue('c3-l3-log')), cites: [] },
    { id: 'C3-L3-H-05', when: not(has.clue('c3-tracks')), cites: [] },
  ], review: 'C3-L3-H-06', exhausted: 'UI-hint.klubokEmpty' }, shell: null },
  minigames: [
    soundGame('c3l3-sound', 3),
    { id: 'c3l3-magnifier', skill: 'magnifier', config: { kind: 'magnifier', targets: [
      { id: 'cord', label: 'C3-5-B01', required: true, reply: ['C3-5-02', 'C3-5-03'] },
      { id: 'wax', label: 'C3-5-B03', required: true, reply: ['C3-5-05'] },
      { id: 'window', label: 'C3-5-B04', required: true, reply: ['C3-L2-4-02', 'C3-L2-4-03'] },
      { id: 'tools', label: 'C3-5-B05', required: true, reply: ['C3-L2-4-04'] },
      { id: 'closed-book', label: 'C3-5-B06', required: true, reply: ['C3-L3-5-01'] },
    ], afterFirst: [], afterFirstSkill: null, assistAfterMisses: 3 } },
    { id: 'c3l3-tracks', skill: 'tracks', config: { kind: 'tracks', steps: [
      { id: 'owl1', prompt: null, pageSize: 3, options: [opt('magpie', 'C3-6-B01', false, 'C3-6-02'), opt('firefly', 'C3-6-B02', false, 'C3-6-03'), opt('owl', 'C3-6-B03', true, 'C3-6-04')] },
      { id: 'owl2', prompt: null, pageSize: 3, options: [opt('beaver', 'C3-6-B04', false, 'C3-L2-5-01'), opt('raccoon', 'C3-6-B05', false, 'C3-L3-6-01'), opt('owl', 'C3-6-B03', true, 'C3-6-04')] },
    ], question: null } },
    { id: 'c3l3-blink', skill: 'read-blink', config: { kind: 'read-blink', drawing: ['dot', 'dot', 'dash'], lessons: [
      { ...opt('hello', 'C3-L3-7-B01', true), pattern: ['dot', 'dot', 'dash'] },
      { ...opt('friends', 'C3-L3-7-B02', false, 'C3-L3-7-03'), pattern: ['dash', 'dot', 'dash'] },
      { ...opt('night', 'C3-L3-7-B03', false, 'C3-L3-7-03'), pattern: ['dash', 'dash'] },
    ], wrong: ['C3-L3-7-03'] } },
    { id: 'c3l3-timeline', skill: 'timeline', config: { kind: 'timeline', items: [
      { id: 't19', time: '19:00', label: 'C3-L2-6-B01' },
      { id: 't20', time: '20:00', label: 'C3-L2-6-B02' },
      { id: 't2030', time: '20:30', label: 'C3-L3-8-B01' },
      { id: 't21', time: '21:00', label: 'C3-L2-6-B03' },
      { id: 't22', time: '22:00', label: 'C3-L2-6-B04' },
    ], solution: ['t19', 't20', 't2030', 't21', 't22'], wrong: ['C3-L2-6-W01'] } },
    lightGame('c3l3-light', 3),
  ],
  facts, glossary, rewards: baseRewards(3), collections, activities: [activity], comfort: commonComfort,
  cutscenes: [intro(3, 'C3-L3-1'), note(3), revealCutscene(3, 'C3-L3-10'), rewardCutscene(3)],
  notebookPages: [secretNotesPage],
  decisions: [
    { id: 'C3L3-D1', text: 'Свой световой сигнал смоделирован полем own в light-signals: ребёнок собирает 3–5 огоньков.', ref: 'D22' },
    { id: 'C3L3-D2', text: 'Рисунок мышат — добросовестная ошибка; сам рисунок нужен только для У5.', ref: 'D04' },
    { id: 'C3L3-T25', text: 'Ролики T25: вступление, тайная заметка, разрешение и награда. Игровые эффекты остаются шагами после роликов.', ref: 'T25' },
  ],
};
