// Child-facing interface labels. Voiced labels come from C's shared pack (`UI-<key>` lines);
// until a key exists there, the built-in text below is shown text-only (no invented narration).
import type { LineView } from '@fluffy/game-core';

export const UI_TEXT: Record<string, string> = {
  'title.play': 'Играть',
  'title.name': 'Пушистое бюро расследований',
  'profile.choose': 'Кто играет?',
  'profile.new': 'Новый сыщик',
  'profile.full': 'Мест больше нет',
  'avatar.species.kitten': 'Котёнок',
  'avatar.species.fox': 'Лисёнок',
  'avatar.species.mouse': 'Мышонок',
  'avatar.species.squirrel': 'Бельчонок',
  'avatar.species.puppy': 'Щенок',
  'avatar.name.prompt': 'Как тебя зовут?',
  'avatar.name.field': 'Имя одним словом',
  'avatar.name.invalid': 'Нужно одно слово, от 2 до 12 букв.',
  'avatar.skip': 'Пропустить',
  'avatar.done': 'Готово',
  'scarf.honey': 'Медовый',
  'scarf.sage': 'Шалфейный',
  'scarf.rose': 'Розовый',
  'scarf.sky': 'Небесный',
  'scarf.berry': 'Черничный',
  'scarf.mint': 'Мятный',
  'hud.pause': 'Пауза',
  'hud.notebook': 'Блокнот',
  'hud.map': 'Карта',
  'hud.lamp': 'Лампа смелости',
  'hud.replay': 'Повторить',
  'hud.next': 'Дальше',
  'hud.klubok': 'Клубок',
  'hud.shell': 'Телефон-ракушка',
  'hud.help': 'Помоги заполнить',
  'hud.version': 'Приглашу на разговор',
  'hud.guess': 'Сказать догадку',
  'hud.back': 'Назад',
  'hud.close': 'Закрыть',
  'hud.ear': 'Послушать',
  'hud.more': 'Ещё варианты',
  'hud.list': 'Список предметов',
  'pause.title': 'Пауза',
  'pause.continue': 'Продолжить',
  'pause.settings': 'Настройки',
  'pause.restartCase': 'Начать дело заново',
  'pause.restartConfirm': 'Начать дело заново? Улики забудутся.',
  'pause.yes': 'Да',
  'pause.no': 'Нет',
  'pause.menu': 'В главное меню',
  'pause.encyclopedia': 'Энциклопедия',
  'pause.glossary': 'Словарик',
  'pause.album': 'Альбом',
  'notebook.confirmed': 'Точно да',
  'notebook.excluded': 'Точно нет',
  'notebook.unknown': 'Пока не знаю',
  'notebook.clear': 'Убрать стикер',
  'notebook.clues': 'Улики',
  'notebook.pick': 'Выбери по одной карточке в каждой колонке.',
  'difficulty.title': 'Выбери сложность',
  'difficulty.1': 'Сложность 1',
  'difficulty.2': 'Сложность 2',
  'difficulty.3': 'Сложность 3',
  'difficulty.1.desc': 'Три подозреваемых и много подсказок.',
  'difficulty.2.desc': 'Четыре подозреваемых, подсказки загадочнее.',
  'difficulty.3.desc': 'Пять подозреваемых и три клубка.',
  'difficulty.start': 'Начать дело',
  'settings.title': 'Настройки',
  'settings.voice': 'Голос',
  'settings.music': 'Музыка',
  'settings.effects': 'Звуки',
  'settings.textSize': 'Размер букв',
  'settings.readable': 'Шрифт для чтения',
  'settings.calm': 'Спокойная анимация',
  'settings.readChoices': 'Читать варианты вслух',
  'settings.on': 'Вкл',
  'settings.off': 'Выкл',
  'settings.system': 'Как в системе',
  rotate: 'Поверни планшет',
  'break.title': 'Пора отдохнуть!',
  'break.body': 'Мы всё сохранили.',
  'break.rest': 'Отдохнуть',
  'break.more': 'Ещё немного',
  'break.resting': 'Отдыхаем. Нажми, когда захочешь вернуться.',
  'parent.enter': 'Для взрослых',
  'parent.hold': 'Нажми и держи',
  'save.saved': 'Сохранено',
  'save.saving': 'Сохраняем…',
  'save.failed': 'Не получилось сохранить. Попробуем ещё?',
  'save.retry': 'Ещё раз',
  'save.otherTab': 'Игра открыта в другом окне.',
  'save.useHere': 'Играть здесь',
  'rewards.buttons': 'Пуговки',
  'rewards.hearts': 'Сердечки доброты',
  'rewards.rank': 'Звание',
  'office.place': 'Поставить сюда',
  'office.title': 'Контора',
  'office.slot.shelf': 'Полка',
  'office.slot.window': 'Окно',
  'office.slot.table': 'Стол',
  'office.cases': 'Дела',
  'album.empty': 'Здесь появятся стикеры за дела.',
  'encyclopedia.empty': 'Здесь появятся факты «А ты знал?».',
  'glossary.empty': 'Здесь появятся слова сыщика.',
  'map.locked': 'Сюда пока рано',
  'case.complete': 'Дело раскрыто!',
  'case.prologue': 'Первый день стажёра',
  'case.case01': 'Пирог, которого не было',
  'case.continue': 'Продолжить дело',
  'rank.intern': 'Стажёр',
  'rank.assistant': 'Помощник сыщика',
  'rank.junior': 'Младший детектив',
  'rank.detective': 'Детектив',
  'rank.master': 'Магистр Лапы',
  'cutscene.skip': 'Пропустить ролик',
  'cutscene.replay': 'Смотреть сначала',
  'voice.textOnly': 'Без голоса: читай текст',
  'voice.blocked': 'Нажми, чтобы включить звук',
};

export interface Label {
  key: string;
  text: string;
  /** Spoken label line, when C's shared pack provides one. */
  line: LineView | null;
}

export type LabelLookup = (key: string, values?: Record<string, string>) => Label;

export function createLabels(sharedLines: Map<string, LineView>): LabelLookup {
  return (key, values) => {
    const line = sharedLines.get(`UI-${key}`) ?? null;
    let text = line?.text ?? UI_TEXT[key] ?? key;
    for (const [name, value] of Object.entries(values ?? {}))
      text = text.replaceAll(`{${name}}`, value);
    return { key, text, line };
  };
}
