import { all, cl, goto, has, L, menu, minigame, not, opt as mopt, reveal, seq, skill, when, type VariantSource } from '../../tools/content/dsl.ts';
import { activity, alleyScene, and, cabinetScene, collections, comfort, commonCutscenes, directionsMinigame, eq, facts, factsScene, glossary, intended, ne, officeIntro, opt, rewardScene, versionIntro, what, where, who } from './common.ts';

const HUB = 'C6-L2-HUB';
const ready = all(has.clue('c6-display'), has.clue('c6-time'), has.clue('c6-compass'), has.clue('c6-route'));

export const level2: VariantSource = {
  pack: 'case06-l2', kind: 'case', title: 'C6-TITLE', case: { number: 6, level: 2 }, start: 'C6-L2-1',
  scenes: [
    { id: 'C6-L2-1', title: 'Завязка', location: 'mayor-office', cast: ['pudding', 'khvosts', 'watsony'], presentation: 'hub', steps: [
      ...officeIntro([L('C6-L2-1-01'), L('C6-L2-1-02')]),
      menu('C6-L2-M', null, [mopt('display', 'C6-1-B01', 'C6-L2-2', { hideWhen: has.visited('C6-L2-2') }), mopt('time', 'C6-1-B02', 'C6-L2-3', { hideWhen: has.visited('C6-L2-3') }), mopt('moss', 'C6-1-B03', 'C6-4', { hideWhen: has.visited('C6-4'), optional: true }), mopt('oak', 'C6-1-B04', 'C6-L2-4', { when: all(has.clue('c6-display'), has.clue('c6-time')), hideWhen: has.visited('C6-L2-4') })]),
    ] },
    { id: 'C6-L2-2', title: 'Витрина: Лупа', location: 'mayor-office', cast: ['khvosts', 'watsony'], presentation: 'minigame', steps: [skill('magnifier', [L('C6-L2-2-01')]), minigame('c6l2-magnifier'), ...seq('C6-2-', 2, 7), ...seq('C6-L2-2-', 2, 4), L('C6-2-08'), reveal('c6-display'), goto(HUB)] },
    { id: 'C6-L2-3', title: 'Лента времени', location: 'town-square', cast: ['stella', 'fitilyok', 'khvosts', 'watsony'], presentation: 'minigame', steps: [skill('timeline', [L('C6-3-01'), L('C6-3-02')]), L('C6-L2-3-02'), minigame('c6l2-timeline'), L('C6-L2-3-03'), L('C6-L2-3-04'), ...seq('C6-3-', 4, 8), reveal('c6-time'), goto(HUB)] },
    { id: 'C6-4', title: 'Мэр и мох', location: 'old-oak', cast: ['pudding', 'khvosts'], presentation: 'dialogue', steps: [...seq('C6-4-', 1, 3), goto(HUB)] },
    { id: HUB, title: 'Мэрия: выбор', location: 'mayor-office', cast: ['pudding', 'khvosts', 'watsony'], presentation: 'hub', steps: [when(all(ready, not(has.visited('C6-L2-6'))), [goto('C6-L2-6')]), menu('C6-L2-HM', null, [mopt('display', 'C6-1-B01', 'C6-L2-2', { hideWhen: has.visited('C6-L2-2') }), mopt('time', 'C6-1-B02', 'C6-L2-3', { hideWhen: has.visited('C6-L2-3') }), mopt('moss', 'C6-1-B03', 'C6-4', { hideWhen: has.visited('C6-4'), optional: true }), mopt('oak', 'C6-1-B04', 'C6-L2-4', { when: all(has.clue('c6-display'), has.clue('c6-time')), hideWhen: has.visited('C6-L2-4') })])] },
    { id: 'C6-L2-4', title: 'Компас у Старого Дуба', location: 'old-oak', cast: ['pudding', 'khvosts', 'watsony'], presentation: 'minigame', steps: [...seq('C6-5-', 1, 7), L('C6-5-N01'), skill('compass', [L('C6-5-08'), L('C6-5-09')]), minigame('c6l2-compass'), L('C6-5-10'), L('C6-L2-4-N01'), ...seq('C6-L2-4-', 1, 3), reveal('c6-compass'), goto('C6-L2-5')] },
    { id: 'C6-L2-5', title: 'Маршрут по компасу', location: 'fountain-square', cast: ['khvosts'], presentation: 'minigame', steps: [skill('compass-route', [L('C6-L2-5-01'), L('C6-L2-5-02')]), minigame('c6l2-route'), L('C6-L2-5-03'), L('C6-L2-5-04'), L('C6-5-13'), L('C6-5-15'), reveal('c6-route'), goto(HUB)] },
    versionIntro('C6-L2-6', HUB), cabinetScene('C6-L2-8', [L('C6-L2-7-01'), L('C6-L2-7-02'), L('C6-L2-7-03')]), alleyScene('C6-L2-8', 2), { ...factsScene(), steps: [...factsScene().steps, goto('C6-10')] }, rewardScene(2),
  ],
  logic: {
    axes: [{ id: 'who', title: 'C6-AX-who', values: [who.shadow, who.stella, who.mice, who.fitilyok] }, { id: 'where', title: 'C6-AX-where', values: [where.roots, where.lighthouse, where.garden, where.hollow] }, { id: 'what', title: 'C6-AX-what', values: [what.quest, what.theft, what.lost, what.cleaning] }], intended,
    clues: [
      { id: 'c6-display', title: 'C6-CL-display', required: true, predicate: and(ne('who', 'fitilyok'), ne('what', 'theft'), ne('what', 'lost'), ne('what', 'cleaning')), requires: [], source: 'C6-L2-2', summary: 'Записка про игру; карточки без пыльцы, не Фитилёк и не чистка.' },
      { id: 'c6-time', title: 'C6-CL-time', required: true, predicate: and(ne('who', 'stella'), ne('who', 'mice')), requires: [], source: 'C6-L2-3', summary: 'Сухие карточки после дождя; мышата спали с двух; Стелла спала до шести.' },
      { id: 'c6-compass', title: 'C6-CL-compass', required: true, predicate: and(ne('where', 'lighthouse'), ne('where', 'garden'), eq('what', 'quest')), requires: ['c6-display', 'c6-time'], source: 'C6-L2-4', summary: 'Карта с ориентирами ведёт к Старому Дубу и игре-квесту.' },
      { id: 'c6-route', title: 'C6-CL-route', required: true, predicate: and(eq('where', 'roots'), ne('where', 'hollow')), requires: ['c6-compass'], source: 'C6-L2-5', summary: 'Маршрут от фонтана приходит к корням, а дупло высоко.' },
    ], version: { button: 'C6-B-version', available: has.visited('C6-L2-6'), onSolved: 'C6-7' },
    wrongVersion: { intro: [cl('C6-6-03')], byValue: [
      { axis: 'who', value: 'stella', clues: ['c6-time'], lines: [cl('C6-6-04')] }, { axis: 'who', value: 'mice', clues: ['c6-time'], lines: [cl('C6-6-05')] }, { axis: 'who', value: 'fitilyok', clues: ['c6-display'], lines: [cl('C6-L2-6-01')] },
      { axis: 'where', value: 'lighthouse', clues: ['c6-compass'], lines: [cl('C6-6-06')] }, { axis: 'where', value: 'garden', clues: ['c6-compass'], lines: [cl('C6-6-06')] }, { axis: 'where', value: 'hollow', clues: ['c6-route'], lines: [cl('C6-L2-6-02')] },
      { axis: 'what', value: 'theft', clues: ['c6-display'], lines: [cl('C6-6-07')] }, { axis: 'what', value: 'lost', clues: ['c6-display'], lines: [cl('C6-6-08')] }, { axis: 'what', value: 'cleaning', clues: ['c6-display'], lines: [cl('C6-L2-6-03')] },
    ], outro: [cl('C6-6-09')] },
    redHerrings: [ { id: 'rh-c6-theft', summary: 'Пустая витрина похожа на кражу.', presentedBy: ['C6-1-02'], explainedBy: ['C6-7-09'] }, { id: 'rh-c6-stella', summary: 'Стелла часто носит бумажки.', presentedBy: ['C6-1-06'], explainedBy: ['C6-7-10'] }, { id: 'rh-c6-moss', summary: 'Мох не показывает север.', presentedBy: ['C6-4-01', 'C6-5-05'], explainedBy: ['C6-5-07', 'C6-7-11'] }, { id: 'rh-c6-fitilyok', summary: 'Фитилёк не спит ночью, но оставил бы пыльцу.', presentedBy: ['C6-L2-1-01'], explainedBy: ['C6-L2-7-01'] }, { id: 'rh-c6-hollow', summary: 'Дупло на том же дубе, но маршрут приводит к корням.', presentedBy: ['C6-L2-4-01'], explainedBy: ['C6-L2-7-02', 'C6-L2-7-03'] }],
  },
  notebookHelp: { mode: 'suggest', marks: [
    { axis: 'who', value: 'shadow', mark: 'confirmed', clues: ['c6-display', 'c6-time'], line: 'C6-NB-01' }, { axis: 'who', value: 'stella', mark: 'excluded', clues: ['c6-time'], line: 'C6-NB-02' }, { axis: 'who', value: 'mice', mark: 'excluded', clues: ['c6-time'], line: 'C6-NB-03' }, { axis: 'who', value: 'fitilyok', mark: 'excluded', clues: ['c6-display'], line: 'C6-NB-04' },
    { axis: 'where', value: 'roots', mark: 'confirmed', clues: ['c6-route'], line: 'C6-NB-06' }, { axis: 'where', value: 'lighthouse', mark: 'excluded', clues: ['c6-compass'], line: 'C6-NB-07' }, { axis: 'where', value: 'garden', mark: 'excluded', clues: ['c6-compass'], line: 'C6-NB-07' }, { axis: 'where', value: 'hollow', mark: 'excluded', clues: ['c6-route'], line: 'C6-NB-08' },
    { axis: 'what', value: 'quest', mark: 'confirmed', clues: ['c6-display', 'c6-compass'], line: 'C6-NB-10' }, { axis: 'what', value: 'theft', mark: 'excluded', clues: ['c6-display'], line: 'C6-NB-11' }, { axis: 'what', value: 'lost', mark: 'excluded', clues: ['c6-display'], line: 'C6-NB-12' }, { axis: 'what', value: 'cleaning', mark: 'excluded', clues: ['c6-display'], line: 'C6-NB-13' },
  ], pointers: [], nothing: 'UI-notebook.nothing' },
  hints: { klubok: { speaker: 'khvosts', precision: 'exact', allowance: 3, rules: [{ id: 'C6-L2-H-01', when: not(has.clue('c6-display')), cites: [] }, { id: 'C6-L2-H-02', when: not(has.clue('c6-time')), cites: [] }, { id: 'C6-L2-H-03', when: all(has.clue('c6-display'), has.clue('c6-time'), not(has.clue('c6-compass'))), cites: ['c6-display', 'c6-time'] }, { id: 'C6-L2-H-04', when: all(has.clue('c6-compass'), not(has.clue('c6-route'))), cites: ['c6-compass'] }, { id: 'C6-L2-H-05', when: has.visited('C6-L2-6'), cites: ['c6-display', 'c6-time', 'c6-compass', 'c6-route'] }], review: 'C6-L2-H-05', exhausted: 'UI-hint.klubokEmptyShell' }, shell: { speaker: 'watsony', precision: 'vague', allowance: null, rules: [{ id: 'C6-L2-R-01', when: not(has.clue('c6-display')), cites: [] }, { id: 'C6-R-04', when: not(has.clue('c6-time')), cites: [] }, { id: 'C6-L2-R-02', when: all(has.clue('c6-display'), has.clue('c6-time'), not(has.clue('c6-compass'))), cites: ['c6-display', 'c6-time'] }, { id: 'C6-L2-R-03', when: all(has.clue('c6-compass'), not(has.clue('c6-route'))), cites: ['c6-compass'] }], review: 'C6-L2-R-02', exhausted: null } },
  minigames: [
    { id: 'c6l2-magnifier', skill: 'magnifier', config: { kind: 'magnifier', targets: [{ id: 'lock', label: 'C6-2-B01', required: true, reply: ['C6-2-02'] }, { id: 'note', label: 'C6-2-B02', required: true, reply: ['C6-2-03', 'C6-2-04'] }, { id: 'card', label: 'C6-2-B03', required: true, reply: ['C6-2-05'] }, { id: 'clean', label: 'C6-2-B04', required: true, reply: ['C6-L2-2-02', 'C6-L2-2-03'] }], afterFirst: [], afterFirstSkill: null, assistAfterMisses: 3 } },
    { id: 'c6l2-timeline', skill: 'timeline', config: { kind: 'timeline', items: [{ id: 'rain', time: '2:30', label: 'C6-3-B02' }, { id: 'mice', time: '3:00', label: 'C6-3-B03' }, { id: 'fitilyok', time: '4:30', label: 'C6-3-B04' }, { id: 'mayor', time: '5:00', label: 'C6-3-B05' }, { id: 'stella', time: '6:00', label: 'C6-3-B06' }], solution: ['rain', 'mice', 'fitilyok', 'mayor', 'stella'], wrong: ['C6-3-03'] } },
    { id: 'c6l2-compass', skill: 'compass', config: { kind: 'staged', mechanic: 'Компас', description: 'Повернуть карту к северу; крестик у Старого Дуба.', steps: [{ id: 'map', prompt: 'C6-5-04', pageSize: 3, options: [opt('left', 'C6-5-B04', false, 'C6-5-10'), opt('right', 'C6-5-B05', false, 'C6-5-10'), opt('oak', 'C6-5-B06', true, 'C6-L2-4-N01')] }], lines: ['C6-5-10', 'C6-L2-4-N01'] } },
    { id: 'c6l2-route', skill: 'compass-route', config: { kind: 'staged', mechanic: 'Маршрут по компасу', description: 'От фонтана два шага на север и один на восток.', steps: [{ id: 'step1', prompt: 'C6-L2-5-01', pageSize: 3, options: [opt('n', 'C6-L2-5-B01', true, 'C6-L2-5-02'), opt('e', 'C6-L2-5-B02', false, 'C6-L2-5-03'), opt('s', 'C6-L2-5-B03', false, 'C6-L2-5-03')] }, { id: 'step2', prompt: 'C6-L2-5-02', pageSize: 3, options: [opt('n', 'C6-L2-5-B01', true, 'C6-L2-5-02'), opt('e', 'C6-L2-5-B02', false, 'C6-L2-5-03'), opt('w', 'C6-L2-5-B04', false, 'C6-L2-5-03')] }, { id: 'step3', prompt: 'C6-L2-5-02', pageSize: 3, options: [opt('e', 'C6-L2-5-B02', true, 'C6-L2-5-04'), opt('n', 'C6-L2-5-B01', false, 'C6-L2-5-03'), opt('s', 'C6-L2-5-B03', false, 'C6-L2-5-03')] }], lines: ['C6-L2-5-03', 'C6-L2-5-04'] } },
    directionsMinigame('c6l2-alley', 2),
  ], facts, glossary, rewards: ['rw-c6-badge', 'rw-c6-buttons-l2', 'rw-c6-sticker-l2', 'rw-c6-decor-compass', 'rw-c6-title-detective', 'rw-c6-activity'], collections, activities: [activity], comfort, cutscenes: commonCutscenes.map((c) => c.scene === 'C6-8' ? { ...c, scene: 'C6-L2-8' } : c), decisions: [
    { id: 'C6L2-D1', text: 'Сложность 2 явно расширяет C6-5-11: крестик только у Старого Дуба, а корни доказывает маршрут.', ref: 'R04' },
    { id: 'C6L2-D2', text: 'Ракушка расплывчатая; Клубок точный с лимитом три.', ref: 'D03' },
  ],
};


