// Shared pack: speakers, skills (mechanics), child-facing interface labels (R06),
// pronunciation lexicon, and the reward catalog (T11).
import { added, finaleHearts, lines, type SharedSource } from '../../tools/content/dsl.ts';

const R06 = 'R06';
const ui = (reason = 'Подпись интерфейса получает стабильный ID и озвучку') => added(reason, R06);

const uiLines = lines('shared/ui', 'label', [
  // Interface labels requested by G (id = UI-<key>)
  ['UI-title.play', 'narrator', 'Играть', ui()],
  ['UI-profile.choose', 'narrator', 'Кто играет?', ui()],
  ['UI-profile.new', 'narrator', 'Новый сыщик', ui()],
  ['UI-profile.full', 'narrator', 'Мест больше нет', ui()],
  ['UI-avatar.species.kitten', 'narrator', 'Котёнок', ui('Подпись карточки выбора животного (P0-02)')],
  ['UI-avatar.species.fox', 'narrator', 'Лисёнок', ui('Подпись карточки выбора животного (P0-02)')],
  ['UI-avatar.species.mouse', 'narrator', 'Мышонок', ui('Подпись карточки выбора животного (P0-02)')],
  ['UI-avatar.species.squirrel', 'narrator', 'Бельчонок', ui('Подпись карточки выбора животного (P0-02)')],
  ['UI-avatar.species.puppy', 'narrator', 'Щенок', ui('Подпись карточки выбора животного (P0-02)')],
  ['UI-avatar.name.prompt', 'narrator', 'Напиши своё имя.', ui('Поле ввода имени (P0-03)')],
  ['UI-avatar.name.default', 'narrator', 'Стажёр', ui('Имя по умолчанию при пропуске (T04)')],
  ['UI-avatar.skip', 'narrator', 'Пропустить', ui()],
  ['UI-avatar.done', 'narrator', 'Готово', ui()],
  ['UI-scarf.honey', 'narrator', 'Медовый', ui('Цвет шарфика (P0-04)')],
  ['UI-scarf.sage', 'narrator', 'Зелёный', ui('Цвет шарфика (P0-04)')],
  ['UI-scarf.rose', 'narrator', 'Розовый', ui('Цвет шарфика (P0-04)')],
  ['UI-scarf.sky', 'narrator', 'Голубой', ui('Цвет шарфика (P0-04)')],
  ['UI-scarf.berry', 'narrator', 'Ягодный', ui('Цвет шарфика (P0-04)')],
  ['UI-scarf.mint', 'narrator', 'Мятный', ui('Цвет шарфика (P0-04)')],
  ['UI-hud.pause', 'narrator', 'Пауза', ui()],
  ['UI-hud.notebook', 'narrator', 'Блокнот', ui()],
  ['UI-hud.map', 'narrator', 'Карта', ui()],
  ['UI-hud.lamp', 'narrator', 'Лампа смелости', ui()],
  ['UI-hud.replay', 'narrator', 'Повторить', ui()],
  ['UI-hud.next', 'narrator', 'Дальше', ui()],
  ['UI-hud.klubok', 'narrator', 'Клубок', ui()],
  ['UI-hud.shell', 'narrator', 'Телефон-ракушка', ui()],
  ['UI-hud.help', 'narrator', 'Помоги заполнить', ui()],
  ['UI-hud.version', 'narrator', 'Приглашу на разговор', ui('Кнопка проверки версии (C1-6)')],
  ['UI-hud.guess', 'narrator', 'Сказать догадку', ui('Кнопка проверки догадки (P2)')],
  ['UI-hud.back', 'narrator', 'Назад', ui()],
  ['UI-hud.close', 'narrator', 'Закрыть', ui()],
  ['UI-hud.ear', 'narrator', 'Послушать', ui()],
  ['UI-pause.title', 'narrator', 'Пауза', ui()],
  ['UI-pause.continue', 'narrator', 'Продолжить', ui()],
  ['UI-pause.settings', 'narrator', 'Настройки', ui()],
  ['UI-pause.restartCase', 'narrator', 'Начать дело заново', ui('Смена сложности внутри дела (D02)')],
  ['UI-pause.restartConfirm', 'narrator', 'Начать дело заново? Улики забудутся.', ui()],
  ['UI-pause.yes', 'narrator', 'Да', ui()],
  ['UI-pause.no', 'narrator', 'Нет', ui()],
  ['UI-pause.menu', 'narrator', 'В главное меню', ui()],
  ['UI-pause.encyclopedia', 'narrator', 'Энциклопедия', ui()],
  ['UI-pause.glossary', 'narrator', 'Словарик', ui()],
  ['UI-pause.album', 'narrator', 'Альбом', ui()],
  ['UI-notebook.title', 'narrator', 'Блокнот сыщика', ui()],
  ['UI-notebook.confirmed', 'narrator', 'Точно да', ui()],
  ['UI-notebook.excluded', 'narrator', 'Точно нет', ui()],
  ['UI-notebook.unknown', 'narrator', 'Пока не знаю', ui()],
  ['UI-notebook.clear', 'narrator', 'Убрать стикер', ui()],
  ['UI-notebook.clues', 'narrator', 'Улики', ui()],
  ['UI-notebook.nothing', 'watsony', 'Пока нечего вписать. Найдём ещё улики!', ui('«Помоги заполнить», когда предложить нечего (Q16)')],
  ['UI-notebook.allDone', 'watsony', 'Всё уже вписано! Блокнот в полном порядке.', ui('«Помоги заполнить», когда стикеры совпадают с уликами')],
  ['UI-difficulty.title', 'narrator', 'Выбери сложность', ui('T22')],
  ['UI-difficulty.1', 'narrator', 'Лёгкая', ui('T22')],
  ['UI-difficulty.1.desc', 'narrator', 'Три улики, ракушка всё подскажет.', ui('Описание сложности (T22, D03)')],
  ['UI-difficulty.2', 'narrator', 'Средняя', ui('T22')],
  ['UI-difficulty.2.desc', 'narrator', 'Четыре улики, ракушка только намекает.', ui('Описание сложности (T22, D03)')],
  ['UI-difficulty.3', 'narrator', 'Трудная', ui('T22')],
  ['UI-difficulty.3.desc', 'narrator', 'Пять улик и только три клубка.', ui('Описание сложности (T22, D03)')],
  ['UI-difficulty.start', 'narrator', 'Начать дело', ui()],
  ['UI-settings.title', 'narrator', 'Настройки', ui()],
  ['UI-settings.voice', 'narrator', 'Голос', ui()],
  ['UI-settings.music', 'narrator', 'Музыка', ui()],
  ['UI-settings.effects', 'narrator', 'Звуки', ui()],
  ['UI-settings.textSize', 'narrator', 'Размер букв', ui()],
  ['UI-settings.readable', 'narrator', 'Шрифт для чтения', ui()],
  ['UI-settings.calm', 'narrator', 'Спокойная анимация', ui()],
  ['UI-settings.readChoices', 'narrator', 'Читать варианты вслух', ui('T06')],
  ['UI-settings.on', 'narrator', 'Включено', ui()],
  ['UI-settings.off', 'narrator', 'Выключено', ui()],
  ['UI-rotate', 'narrator', 'Поверни планшет', ui('T02')],
  ['UI-break.title', 'narrator', 'Пора отдохнуть!', ui('T16')],
  ['UI-break.body', 'narrator', 'Мы всё сохранили.', ui('T16')],
  ['UI-break.rest', 'narrator', 'Отдохнуть', ui('T16')],
  ['UI-break.more', 'narrator', 'Ещё немного', ui('T16')],
  ['UI-parent.enter', 'narrator', 'Для взрослых', ui('T17')],
  ['UI-parent.hold', 'narrator', 'Нажми и держи', ui('T17')],
  ['UI-save.saved', 'narrator', 'Сохранено', ui()],
  ['UI-save.failed', 'narrator', 'Не получилось сохранить. Попробуем ещё?', ui()],
  ['UI-save.retry', 'narrator', 'Ещё раз', ui()],
  ['UI-save.otherTab', 'narrator', 'Игра открыта в другом окне.', ui('Q09')],
  ['UI-save.useHere', 'narrator', 'Играть здесь', ui('Q09')],
  ['UI-rewards.buttons', 'narrator', 'Пуговки', ui()],
  ['UI-rewards.hearts', 'narrator', 'Сердечки доброты', ui()],
  ['UI-rewards.rank', 'narrator', 'Звание', ui()],
  ['UI-rewards.newWord', 'narrator', 'Новое слово в Словарике!', ui()],
  ['UI-rewards.newFact', 'narrator', 'Новая карточка в Энциклопедии!', ui()],
  ['UI-office.place', 'narrator', 'Поставить сюда', ui('T12')],
  ['UI-office.title', 'narrator', 'Контора', ui()],
  ['UI-album.empty', 'narrator', 'Альбом пока пустой. Раскрой первое дело!', ui()],
  ['UI-encyclopedia.title', 'narrator', 'Энциклопедия Пушистых Знаний', ui()],
  ['UI-encyclopedia.true', 'narrator', 'Это правда', ui('Рамочка карточки факта (C1-9)')],
  ['UI-encyclopedia.empty', 'narrator', 'Здесь будут карточки с фактами.', ui()],
  ['UI-glossary.title', 'narrator', 'Словарик сыщика', ui()],
  ['UI-glossary.empty', 'narrator', 'Здесь будут слова сыщика.', ui()],
  ['UI-activity.title', 'narrator', 'Настоящее дело', ui('Карточки «со взрослым» (Q25)')],
  ['UI-activity.withAdult', 'narrator', 'Со взрослым', ui('Q25')],
  ['UI-activity.adultStep', 'narrator', 'Это делает взрослый.', ui('Пометка опасного шага (Q25)')],
  ['UI-map.locked', 'narrator', 'Сюда пока рано', ui()],
  ['UI-hint.klubokEmptyShell', 'khvosts', 'Клубки кончились. Можно позвонить Ватсони!', ui('Клубки исчерпаны, ракушка доступна (D03)')],
  ['UI-hint.klubokEmpty', 'khvosts', 'Клубки кончились. Перечитаем Блокнот вместе?', ui('Клубки исчерпаны на сложности 3 (D03)')],
  ['UI-hint.shellRing', 'narrator', 'Звоним Ватсони…', ui()],
  ['UI-case.complete', 'narrator', 'Дело раскрыто!', ui()],
  ['UI-cutscene.skip', 'narrator', 'Пропустить ролик', ui('Кнопка ролика (T25)')],
  ['UI-cutscene.replay', 'narrator', 'Смотреть сначала', ui('Кнопка ролика (T25)')],
  ['UI-family.solo', 'narrator', 'Играем одни', ui('Выбор режима дела 4 (T31)')],
  ['UI-family.family', 'narrator', 'Играем семьёй', ui('Выбор режима дела 4 (T31)')],
  ['UI-family.howMany', 'narrator', 'Сколько игроков?', ui('Семейный режим (T31)')],
  ['UI-family.chooseKeeper', 'narrator', 'Кто будет Хранителем?', ui('Семейный режим (T31)')],
  ['UI-family.passKeeper', 'narrator', 'Передай устройство Хранителю', ui('Экран передачи хода (Q34, T31)')],
  ['UI-family.passOthers', 'narrator', 'Передай устройство остальным', ui('Экран передачи хода (Q34, T31)')],
  ['UI-family.itIsMe', 'narrator', 'Это я', ui('Экран передачи хода (Q34)')],
  ['UI-family.ready', 'narrator', 'Запомнено, прячем', ui('Хранитель скрывает карту; без рода (D05)')],
  ['UI-family.hide', 'narrator', 'Спрятать', ui('Семейный режим (T31)')],
  ['UI-family.ask', 'narrator', 'Задать вопрос', ui('Семейный режим (T31)')],
  ['UI-family.guess', 'narrator', 'Выбрать ответ', ui('Семейный режим (T31)')],
  ['UI-family.yes', 'narrator', 'Да', ui('Ответ на вопрос (T31)')],
  ['UI-family.no', 'narrator', 'Нет', ui('Ответ на вопрос (T31)')],
  ['UI-family.win', 'narrator', 'Победа общая!', ui('Финал семейного режима (Q36)')],
  ['UI-notebook.secretNotes', 'narrator', 'Тайные заметки', ui('Страница Блокнота (T26, D06)')],
  ['UI-notebook.cipherPoster', 'narrator', 'Почтовый шифр Пушистино', ui('Страница Блокнота (T26)')],
  ['UI-offline.caseLater', 'narrator', 'Это дело ещё скачивается. Оно откроется, когда появится интернет.', ui('Выбор дела без сети, пока картинки и голоса не скачались (v0.2.1)')],
  ['UI-cozy.title', 'narrator', 'Уютный денёк', ui('Экран Конторы (T12, D23)')],
  ['UI-cozy.shop', 'narrator', 'Лавка', ui('Магазин (T29)')],
  ['UI-cozy.buy', 'narrator', 'Купить', ui('Магазин (T29)')],
  ['UI-cozy.return', 'narrator', 'Вернуть', ui('Магазин: возврат покупки (Q40)')],
  ['UI-cozy.owned', 'narrator', 'Уже твоё', ui('Магазин (T29)')],
  ['UI-cozy.wear', 'narrator', 'Надеть', ui('Магазин (T29)')],
  ['UI-cozy.place', 'narrator', 'Поставить', ui('Украшения Конторы (T29)')],
  ['UI-cozy.tea', 'narrator', 'Позвать на чай', ui('Чаепитие с жителем (T28)')],
  ['UI-cozy.hats', 'narrator', 'Шапки', ui('Раздел магазина (T29)')],
  ['UI-cozy.scarves', 'narrator', 'Шарфы', ui('Раздел магазина (T29)')],
  ['UI-cozy.decor', 'narrator', 'Украшения', ui('Раздел магазина (T29)')],
  ['UI-rank.new', 'narrator', 'Новое звание!', ui('Звания (D12)')],  // Skill titles
  ['SK-inspect', 'narrator', 'Осмотр', ui()],
  ['SK-replay', 'narrator', 'Ушко: повтор', ui()],
  ['SK-lamp', 'narrator', 'Лампа смелости', ui()],
  ['SK-notebook', 'narrator', 'Блокнот', ui()],
  ['SK-guess', 'narrator', 'Догадка', ui()],
  ['SK-shell', 'narrator', 'Телефон-ракушка', ui()],
  ['SK-pause', 'narrator', 'Пауза', ui()],
  ['SK-map', 'narrator', 'Карта', ui()],
  ['SK-klubki', 'narrator', 'Клубки', ui()],
  ['SK-magnifier', 'narrator', 'Лупа', ui()],
  ['SK-cocoa', 'narrator', 'Чашка какао', ui()],
  ['SK-tracks', 'narrator', 'Кто наследил?', ui()],
  ['SK-version', 'narrator', 'Версия', ui()],
  ['SK-baker', 'narrator', 'Пекарь', ui()],
  ['SK-encyclopedia', 'narrator', 'Энциклопедия', ui()],
  ['SK-cozy-day', 'narrator', 'Уютный денёк', ui()],
  ['SK-timeline', 'narrator', 'Лента времени', ui()],
  ['SK-scent-pairs', 'narrator', 'Пары запахов', ui()],
  ['SK-intro', 'narrator', 'Вступление', ui('Название ролика-вступления (T25)')],
  // Speaker names (character pickers, encyclopedia of heroes)
  ['NM-khvosts', 'narrator', 'Шерлок Хвостс', ui()],
  ['NM-watsony', 'narrator', 'Доктор Ватсони', ui()],
  ['NM-pudding', 'narrator', 'Мэр Пудинг', ui()],
  ['NM-tyopa', 'narrator', 'Енот Тёпа', ui()],
  ['NM-fitilyok', 'narrator', 'Светлячок Фитилёк', ui()],
  ['NM-kartofan', 'narrator', 'Крот Картофан', ui()],
  ['NM-stella', 'narrator', 'Сорока Стелла', ui()],
  ['NM-mouse', 'narrator', 'Мышата Шуршики', ui()],
  ['NM-narrator', 'narrator', 'Рассказчик', ui()],
  // Rewards (T11)
  ['RW-badge-intern', 'narrator', 'Значок стажёра', ui('Название награды (T11)')],
  ['RW-title-intern', 'narrator', 'Звание: Стажёр', ui('Название награды (T11)')],
  ['RW-buttons-5', 'narrator', 'Пять пуговок!', ui('Название награды (T11)')],
  ['RW-buttons-10', 'narrator', 'Десять пуговок!', ui('Название награды (T11)')],
  ['RW-buttons-15', 'narrator', 'Пятнадцать пуговок!', ui('Название награды (T11)')],
  ['RW-buttons-20', 'narrator', 'Двадцать пуговок!', ui('Название награды (T11)')],
  ['RW-heart', 'narrator', 'Сердечко доброты!', ui('Название награды (T11)')],
  ['RW-c1-badge', 'narrator', 'Значок-лапка «Пирог найден»', ui('Название награды (C1-10-02)')],
  ['RW-c1-sticker-1', 'narrator', 'Стикер «Пирог найден», одна звёздочка', ui('Стикер по сложности (Q38)')],
  ['RW-c1-sticker-2', 'narrator', 'Стикер «Пирог найден», две звёздочки', ui('Стикер по сложности (Q38)')],
  ['RW-c1-sticker-3', 'narrator', 'Стикер «Пирог найден», три звёздочки', ui('Стикер по сложности (Q38)')],
  ['RW-c1-decor-basket', 'narrator', 'Корзинка черники для Конторы', ui('Предмет для Конторы (C1-10, T12)')],
  ['RW-c1-activity', 'narrator', 'Карточка «Пирог по рецепту мэра Пудинга»', ui('Карточка «Настоящее дело» (C1-10)')],
]);

export const shared: SharedSource = {
  lines: uiLines,
  speakers: [
    { id: 'narrator', name: 'Рассказчик', nameLabel: 'NM-narrator', species: '—', voiceNote: 'Тёплый спокойный рассказчик; читает подписи, факты, словарик, карточки.' },
    { id: 'khvosts', name: 'Шерлок Хвостс', nameLabel: 'NM-khvosts', species: 'барсук, дедушка', voiceNote: 'Пожилой, добрый, неторопливый; «Элементарно, пушинка!»; пускает пузыри, когда думает.' },
    { id: 'watsony', name: 'Доктор Ватсони', nameLabel: 'NM-watsony', species: 'ежиха', voiceNote: 'Заботливая, чуть забывчивая, улыбчивая; «Записала!.. кажется».' },
    { id: 'pudding', name: 'Мэр Пудинг', nameLabel: 'NM-pudding', species: 'хомяк', voiceNote: 'Суетливый, громкий, добродушный; щёки набиты.' },
    { id: 'tyopa', name: 'Тёпа', nameLabel: 'NM-tyopa', species: 'енот', voiceNote: 'Мягкий добряк-мыловар; легко расстраивается, быстро оттаивает.' },
    { id: 'fitilyok', name: 'Фитилёк', nameLabel: 'NM-fitilyok', species: 'светлячок', voiceNote: 'Звонкий, быстрый, фокусник.' },
    { id: 'kartofan', name: 'Картофан', nameLabel: 'NM-kartofan', species: 'крот', voiceNote: 'Рассеянный садовник, говорит медленно, по-доброму смущается.' },
    { id: 'stella', name: 'Стелла', nameLabel: 'NM-stella', species: 'сорока', voiceNote: 'Бойкая почтальонша, тараторит, честная.' },
    { id: 'mouse', name: 'Мышонок Шуршик', nameLabel: 'NM-mouse', species: 'мышонок', voiceNote: 'Тоненький робкий голосок.' },
    { id: 'damka', name: 'Дамка', nameLabel: 'NM-damka', species: 'бобёрша', voiceNote: 'Смотритель Медового маяка и инженер; деловитая, тёплая (D20).' },
    { id: 'pukhlik', name: 'Пухлик', nameLabel: 'NM-pukhlik', species: 'совёнок', voiceNote: 'Ночной стажёр; тихий, застенчивый, хранит секрет (D07, D09).' },
    { id: 'all', name: 'Все вместе', nameLabel: 'NM-all', species: 'хор', voiceNote: 'Все герои хором.' },
  ],
  skills: [
    'inspect', 'replay', 'lamp', 'notebook', 'guess', 'shell', 'pause', 'map', 'klubki', 'magnifier', 'cocoa',
    'tracks', 'version', 'baker', 'encyclopedia', 'cozy-day', 'timeline', 'scent-pairs', 'intro',
  ].map((id) => ({ id, title: `SK-${id}` })),
  lexicon: [
    { word: 'Хвостс', hint: 'Хво́стс' },
    { word: 'Ватсони', hint: 'Ватсо́ни' },
    { word: 'Пудинг', hint: 'Пу́динг' },
    { word: 'Картофан', hint: 'Картофа́н' },
    { word: 'Фитил', hint: 'Фити́л' },
    { word: 'Стелл', hint: 'Сте́лл' },
    { word: 'Шуршик', hint: 'Шу́ршик' },
    { word: 'Пушистин', hint: 'Пуши́стин' },
    { word: 'пушинка', hint: 'пуши́нка' },
    { word: 'Пироговая', hint: 'Пирогова́я' },
    { word: 'Пироговую', hint: 'Пирогову́ю' },
    { word: 'мыловарн', hint: 'мылова́рн' },
    { word: 'черник', hint: 'черни́к' },
    { word: 'черничн', hint: 'черни́чн' },
    { word: 'Шерлок', hint: 'Ше́рлок' },
    { word: 'Дамк', hint: 'Да́мк' },
    { word: 'Пухлик', hint: 'Пу́хлик' },
    { word: 'щурился', hint: 'щу́рился' },
  ],
  rewards: [
    { id: 'rw-prologue-badge', kind: 'badge', label: 'RW-badge-intern', amount: 1, claimKey: 'prologue:badge' },
    { id: 'rw-prologue-title', kind: 'title', label: 'RW-title-intern', amount: 1, claimKey: 'prologue:title' },
    { id: 'rw-prologue-buttons', kind: 'buttons', label: 'RW-buttons-5', amount: 5, claimKey: 'prologue:buttons' },
    { id: 'rw-c1-heart-tyopa', kind: 'hearts', label: 'RW-heart', amount: 1, claimKey: 'case01:heart:tyopa' },
    { id: 'rw-c1-heart-tyopa-l2', kind: 'hearts', label: 'RW-heart', amount: 1, claimKey: 'case01:l2:heart:tyopa' },
    { id: 'rw-c1-heart-tyopa-l3', kind: 'hearts', label: 'RW-heart', amount: 1, claimKey: 'case01:l3:heart:tyopa' },
    ...finaleHearts(1),
    { id: 'rw-c1-badge', kind: 'badge', label: 'RW-c1-badge', amount: 1, claimKey: 'case01:badge' },
    { id: 'rw-c1-buttons-l1', kind: 'buttons', label: 'RW-buttons-10', amount: 10, claimKey: 'case01:l1:buttons' },
    { id: 'rw-c1-buttons-l2', kind: 'buttons', label: 'RW-buttons-15', amount: 15, claimKey: 'case01:l2:buttons' },
    { id: 'rw-c1-buttons-l3', kind: 'buttons', label: 'RW-buttons-20', amount: 20, claimKey: 'case01:l3:buttons' },
    { id: 'rw-c1-sticker-l1', kind: 'sticker', label: 'RW-c1-sticker-1', amount: 1, claimKey: 'case01:l1:sticker' },
    { id: 'rw-c1-sticker-l2', kind: 'sticker', label: 'RW-c1-sticker-2', amount: 1, claimKey: 'case01:l2:sticker' },
    { id: 'rw-c1-sticker-l3', kind: 'sticker', label: 'RW-c1-sticker-3', amount: 1, claimKey: 'case01:l3:sticker' },
    { id: 'rw-c1-decor-basket', kind: 'decor', label: 'RW-c1-decor-basket', amount: 1, claimKey: 'case01:decor:basket' },
    { id: 'rw-c1-activity', kind: 'activity', label: 'RW-c1-activity', amount: 1, claimKey: 'case01:activity:pie' },
  ],
};
